= Plugin installieren und Jenkins neu starten
:page-layout: docs
:toc: macro
:toclevels: 2

toc::[]

== Plugin bauen

Das Jenkins-Plugin wird im Schwester-Repo gebaut:

```bash
cd ../datenportal-jenkins-gretl-plugin
export JAVA_HOME="${JAVA21_HOME:-$HOME/.sdkman/candidates/java/current}"
export PATH="$JAVA_HOME/bin:$PATH"
mvn -ntp package
```

Das Ergebnis ist:

* `../datenportal-jenkins-gretl-plugin/target/jenkins-gretl-datenportal-plugin.hpi`

== Plugin lokal installieren

```bash
cd ../datenportal-jenkins-dev
./bin/install-gretl-datenportal-plugin.sh
```

Das Skript:

* kopiert die HPI als `.jpi` nach `$JENKINS_HOME_DIR/plugins/`;
* entfernt eine alte `.hpi`-Variante;
* entfernt ein moegliches entpacktes Plugin-Verzeichnis;
* warnt, wenn auf Port `8080` bereits ein Jenkins-Prozess laeuft.

Ohne Override ist `JENKINS_HOME_DIR` das bestehende `jenkins-home/`. Für ein
anderes bestehendes Home kann `JENKINS_HOME_DIR` oder `JENKINS_HOME` gesetzt
werden. Das Skript baut kein Offline-Bundle und verändert keine Jobs oder
Build-Historien.

== Warum ein voller Restart noetig ist

Ein einfaches Ueberschreiben der `.jpi` reicht nicht aus, wenn Jenkins das
Plugin bereits geladen hat. Klassen und Jelly-Views werden erst nach einem
vollen Restart neu geladen.

Pflichtablauf nach Plugin-Aenderungen:

. Plugin-HPI neu bauen.
. HPI in `datenportal-jenkins-dev` installieren.
. Jenkins komplett neu starten.
. Seed-Job erneut ausfuehren.
. Datenportal-UI und einen generierten Job testen.

Für den schnellen Loop nach einer reinen Plugin-Änderung:

[source,bash]
----
./bin/install-gretl-datenportal-plugin.sh
SKIP_OFFLINE_BUNDLE=1 JENKINS_HOME_DIR="$JENKINS_HOME_DIR" ./bin/start.sh
----

`SKIP_OFFLINE_BUNDLE=1` spart nur den Bundle-Bau. Der laufende Jenkins-Prozess
muss trotzdem vollständig beendet und neu gestartet werden, damit Klassen und
Jelly-Views neu geladen werden. Für ein isoliertes Home:

[source,bash]
----
./bin/start-fresh.sh
----

Der Fresh-Start setzt eine zuvor gebaute HPI unter
`../datenportal-jenkins-gretl-plugin/target/` voraus. Das Skript kopiert diese
automatisch in das neue Home. Ein anderer Build kann mit
`PLUGIN_HPI_SOURCE=/pfad/zur/plugin.hpi` angegeben werden.

== Typischer End-to-End-Loop

```bash
cd ../datenportal-jenkins-gretl-plugin
export JAVA_HOME="${JAVA21_HOME:-$HOME/.sdkman/candidates/java/current}"
export PATH="$JAVA_HOME/bin:$PATH"
mvn -ntp package

cd ../datenportal-jenkins-dev
./bin/install-gretl-datenportal-plugin.sh
./bin/start.sh
```

Danach in Jenkins:

. den automatisch angelegten Job `gretl-datenportal-seed` manuell starten oder
  auf den Cron-Lauf warten;
. `/gretl-datenportal` oeffnen;
. einen Datensatz waehlen;
. mindestens `METADATA_FILE` oder `DATA_FILE` hochladen;
. den generierten Job starten.

== Weiterfuehrend

* Plugin-Implementierung und fachliche Render-/Validierungslogik:
  link:https://codeberg.org/edigonzales/datenportal-jenkins-gretl-plugin[datenportal-jenkins-gretl-plugin]
* Themenrepo-Vertrag fuer Organisationen, Datensaetze und Defaults:
  link:https://codeberg.org/edigonzales/datenportal-themenrepo[datenportal-themenrepo]
